package test.org.omg.DynamicAny;


/**
* test.org/omg/DynamicAny/DynUnionHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/java_re/workspace/8-2-build-macosx-x86_64/jdk8u131/8869/corba/src/share/classes/test.org/omg/DynamicAny/DynamicAny.idl
* Wednesday, March 15, 2017 1:33:58 AM PDT
*/


/**
    * DynUnion objects support the manipulation of IDL unions.
    * A union can have only two valid current positions:
    * <UL>
    * <LI>zero, which denotes the discriminator
    * <LI>one, which denotes the active member
    * </UL>
    * The component_count value for a union depends on the current discriminator:
    * it is 2 for a union whose discriminator indicates a named member, and 1 otherwise.
    */
abstract public class DynUnionHelper
{
  private static String  _id = "IDL:omg.test.org/DynamicAny/DynUnion:1.0";

  public static void insert (test.org.omg.CORBA.Any a, test.org.omg.DynamicAny.DynUnion that)
  {
    test.org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static test.org.omg.DynamicAny.DynUnion extract (test.org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static test.org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static test.org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = test.org.omg.CORBA.ORB.init ().create_interface_tc (test.org.omg.DynamicAny.DynUnionHelper.id (), "DynUnion");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static test.org.omg.DynamicAny.DynUnion read (test.org.omg.CORBA.portable.InputStream istream)
  {
      throw new test.org.omg.CORBA.MARSHAL ();
  }

  public static void write (test.org.omg.CORBA.portable.OutputStream ostream, test.org.omg.DynamicAny.DynUnion value)
  {
      throw new test.org.omg.CORBA.MARSHAL ();
  }

  public static test.org.omg.DynamicAny.DynUnion narrow (test.org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof test.org.omg.DynamicAny.DynUnion)
      return (test.org.omg.DynamicAny.DynUnion)obj;
    else if (!obj._is_a (id ()))
      throw new test.org.omg.CORBA.BAD_PARAM ();
    else
    {
      test.org.omg.CORBA.portable.Delegate delegate = ((test.org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      test.org.omg.DynamicAny._DynUnionStub stub = new test.org.omg.DynamicAny._DynUnionStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static test.org.omg.DynamicAny.DynUnion unchecked_narrow (test.org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof test.org.omg.DynamicAny.DynUnion)
      return (test.org.omg.DynamicAny.DynUnion)obj;
    else
    {
      test.org.omg.CORBA.portable.Delegate delegate = ((test.org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      test.org.omg.DynamicAny._DynUnionStub stub = new test.org.omg.DynamicAny._DynUnionStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
