package test.org.omg.DynamicAny;


/**
* test.org/omg/DynamicAny/DynValueCommon.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/java_re/workspace/8-2-build-macosx-x86_64/jdk8u131/8869/corba/src/share/classes/test.org/omg/DynamicAny/DynamicAny.idl
* Wednesday, March 15, 2017 1:33:58 AM PDT
*/


/**
    * DynValueCommon provides operations supported by both the DynValue and DynValueBox interfaces.
    */
public interface DynValueCommon extends DynValueCommonOperations, test.org.omg.DynamicAny.DynAny, test.org.omg.CORBA.portable.IDLEntity
{
} // interface DynValueCommon
