package test.org.omg.PortableServer.POAManagerPackage;


/**
* test.org/omg/PortableServer/POAManagerPackage/State.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/java_re/workspace/8-2-build-macosx-x86_64/jdk8u131/8869/corba/src/share/classes/test.org/omg/PortableServer/poa.idl
* Wednesday, March 15, 2017 1:33:59 AM PDT
*/


/**
	 * Specifies the states for the POAManager
	 */
public class State implements test.org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 4;
  private static test.org.omg.PortableServer.POAManagerPackage.State[] __array = new test.org.omg.PortableServer.POAManagerPackage.State [__size];

  public static final int _HOLDING = 0;
  public static final test.org.omg.PortableServer.POAManagerPackage.State HOLDING = new test.org.omg.PortableServer.POAManagerPackage.State(_HOLDING);
  public static final int _ACTIVE = 1;
  public static final test.org.omg.PortableServer.POAManagerPackage.State ACTIVE = new test.org.omg.PortableServer.POAManagerPackage.State(_ACTIVE);
  public static final int _DISCARDING = 2;
  public static final test.org.omg.PortableServer.POAManagerPackage.State DISCARDING = new test.org.omg.PortableServer.POAManagerPackage.State(_DISCARDING);
  public static final int _INACTIVE = 3;
  public static final test.org.omg.PortableServer.POAManagerPackage.State INACTIVE = new test.org.omg.PortableServer.POAManagerPackage.State(_INACTIVE);

  public int value ()
  {
    return __value;
  }

  public static test.org.omg.PortableServer.POAManagerPackage.State from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new test.org.omg.CORBA.BAD_PARAM ();
  }

  protected State (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class State
