package test.org.omg.PortableInterceptor;


/**
* test.org/omg/PortableInterceptor/IORInterceptor_3_0Helper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/java_re/workspace/8-2-build-macosx-x86_64/jdk8u131/8869/corba/src/share/classes/test.org/omg/PortableInterceptor/Interceptors.idl
* Wednesday, March 15, 2017 1:33:58 AM PDT
*/

abstract public class IORInterceptor_3_0Helper
{
  private static String  _id = "IDL:omg.test.org/PortableInterceptor/IORInterceptor_3_0:1.0";

  public static void insert (test.org.omg.CORBA.Any a, test.org.omg.PortableInterceptor.IORInterceptor_3_0 that)
  {
    test.org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static test.org.omg.PortableInterceptor.IORInterceptor_3_0 extract (test.org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static test.org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static test.org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = test.org.omg.CORBA.ORB.init ().create_interface_tc (test.org.omg.PortableInterceptor.IORInterceptor_3_0Helper.id (), "IORInterceptor_3_0");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static test.org.omg.PortableInterceptor.IORInterceptor_3_0 read (test.org.omg.CORBA.portable.InputStream istream)
  {
      throw new test.org.omg.CORBA.MARSHAL ();
  }

  public static void write (test.org.omg.CORBA.portable.OutputStream ostream, test.org.omg.PortableInterceptor.IORInterceptor_3_0 value)
  {
      throw new test.org.omg.CORBA.MARSHAL ();
  }

  public static test.org.omg.PortableInterceptor.IORInterceptor_3_0 narrow (test.org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof test.org.omg.PortableInterceptor.IORInterceptor_3_0)
      return (test.org.omg.PortableInterceptor.IORInterceptor_3_0)obj;
    else
      throw new test.org.omg.CORBA.BAD_PARAM ();
  }

  public static test.org.omg.PortableInterceptor.IORInterceptor_3_0 unchecked_narrow (test.org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof test.org.omg.PortableInterceptor.IORInterceptor_3_0)
      return (test.org.omg.PortableInterceptor.IORInterceptor_3_0)obj;
    else
      throw new test.org.omg.CORBA.BAD_PARAM ();
  }

}
