package test.org.omg.IOP;


/**
* test.org/omg/IOP/CodecFactoryHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/java_re/workspace/8-2-build-macosx-x86_64/jdk8u131/8869/corba/src/share/classes/test.org/omg/PortableInterceptor/IOP.idl
* Wednesday, March 15, 2017 1:33:58 AM PDT
*/


/**
   * <code>Codecs</code> are obtained from the <code>CodecFactory</code>. 
   * The <code>CodecFactory</code> is obtained through a call to 
   * <code>ORB.resolve_initial_references( "CodecFactory" )</code>.
   */
abstract public class CodecFactoryHelper
{
  private static String  _id = "IDL:omg.test.org/IOP/CodecFactory:1.0";

  public static void insert (test.org.omg.CORBA.Any a, test.org.omg.IOP.CodecFactory that)
  {
    test.org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static test.org.omg.IOP.CodecFactory extract (test.org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static test.org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static test.org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = test.org.omg.CORBA.ORB.init ().create_interface_tc (test.org.omg.IOP.CodecFactoryHelper.id (), "CodecFactory");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static test.org.omg.IOP.CodecFactory read (test.org.omg.CORBA.portable.InputStream istream)
  {
      throw new test.org.omg.CORBA.MARSHAL ();
  }

  public static void write (test.org.omg.CORBA.portable.OutputStream ostream, test.org.omg.IOP.CodecFactory value)
  {
      throw new test.org.omg.CORBA.MARSHAL ();
  }

  public static test.org.omg.IOP.CodecFactory narrow (test.org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof test.org.omg.IOP.CodecFactory)
      return (test.org.omg.IOP.CodecFactory)obj;
    else
      throw new test.org.omg.CORBA.BAD_PARAM ();
  }

  public static test.org.omg.IOP.CodecFactory unchecked_narrow (test.org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof test.org.omg.IOP.CodecFactory)
      return (test.org.omg.IOP.CodecFactory)obj;
    else
      throw new test.org.omg.CORBA.BAD_PARAM ();
  }

}
