package test.org.omg.IOP;


/**
* test.org/omg/IOP/IORHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/java_re/workspace/8-2-build-macosx-x86_64/jdk8u131/8869/corba/src/share/classes/test.org/omg/PortableInterceptor/IOP.idl
* Wednesday, March 15, 2017 1:33:58 AM PDT
*/

abstract public class IORHelper
{
  private static String  _id = "IDL:omg.test.org/IOP/IOR:1.0";

  public static void insert (test.org.omg.CORBA.Any a, test.org.omg.IOP.IOR that)
  {
    test.org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static test.org.omg.IOP.IOR extract (test.org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static test.org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static test.org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (test.org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return test.org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          test.org.omg.CORBA.StructMember[] _members0 = new test.org.omg.CORBA.StructMember [2];
          test.org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = test.org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new test.org.omg.CORBA.StructMember (
            "type_id",
            _tcOf_members0,
            null);
          _tcOf_members0 = test.org.omg.IOP.TaggedProfileHelper.type ();
          _tcOf_members0 = test.org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _members0[1] = new test.org.omg.CORBA.StructMember (
            "profiles",
            _tcOf_members0,
            null);
          __typeCode = test.org.omg.CORBA.ORB.init ().create_struct_tc (test.org.omg.IOP.IORHelper.id (), "IOR", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static test.org.omg.IOP.IOR read (test.org.omg.CORBA.portable.InputStream istream)
  {
    test.org.omg.IOP.IOR value = new test.org.omg.IOP.IOR ();
    value.type_id = istream.read_string ();
    int _len0 = istream.read_long ();
    value.profiles = new test.org.omg.IOP.TaggedProfile[_len0];
    for (int _o1 = 0;_o1 < value.profiles.length; ++_o1)
      value.profiles[_o1] = test.org.omg.IOP.TaggedProfileHelper.read (istream);
    return value;
  }

  public static void write (test.org.omg.CORBA.portable.OutputStream ostream, test.org.omg.IOP.IOR value)
  {
    ostream.write_string (value.type_id);
    ostream.write_long (value.profiles.length);
    for (int _i0 = 0;_i0 < value.profiles.length; ++_i0)
      test.org.omg.IOP.TaggedProfileHelper.write (ostream, value.profiles[_i0]);
  }

}
