package test.org.omg.PortableServer;


/**
* test.org/omg/PortableServer/LifespanPolicyOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/java_re/workspace/8-2-build-macosx-x86_64/jdk8u131/8869/corba/src/share/classes/test.org/omg/PortableServer/poa.idl
* Wednesday, March 15, 2017 1:33:59 AM PDT
*/


/**
	 * The LifespanPolicy specifies the lifespan of the 
	 * objects implemented in the created POA. The default 
	 * is TRANSIENT.
	 */
public interface LifespanPolicyOperations  extends test.org.omg.CORBA.PolicyOperations
{

  /**
  	 * specifies the policy value
  	 */
  test.org.omg.PortableServer.LifespanPolicyValue value ();
} // interface LifespanPolicyOperations
