/*
 * Copyright (c) 2001, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */

package test.org.omg.PortableServer;

/**
* test.org/omg/PortableServer/POAHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../../../../src/share/classes/test.org/omg/PortableServer/poa.idl
* Tuesday, October 23, 2001 1:16:58 PM PDT
*/


/**
 * A POA object manages the implementation of a
 * collection of objects. The POA supports a name space
 * for the objects, which are identified by Object Ids.
 * A POA also provides a name space for POAs. A POA is
 * created as a child of an existing POA, which forms a
 * hierarchy starting with the root POA. A POA object
 * must not be exported to other processes, or
 * externalized with ORB::object_to_string.
 */
abstract public class POAHelper
{
    private static String  _id = "IDL:omg.test.org/PortableServer/POA:2.3";

    public static void insert (test.org.omg.CORBA.Any a,
                               test.org.omg.PortableServer.POA that)
    {
        test.org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
        a.type (type ());
        write (out, that);
        a.read_value (out.create_input_stream (), type ());
    }

    public static test.org.omg.PortableServer.POA extract (test.org.omg.CORBA.Any a)
    {
        return read (a.create_input_stream ());
    }

    private static test.org.omg.CORBA.TypeCode __typeCode = null;
    synchronized public static test.org.omg.CORBA.TypeCode type ()
    {
        if (__typeCode == null)
        {
            __typeCode = test.org.omg.CORBA.ORB.init ().create_interface_tc (test.org.omg.PortableServer.POAHelper.id (), "POA");
        }
        return __typeCode;
    }

    public static String id ()
    {
        return _id;
    }

    public static test.org.omg.PortableServer.POA read (
        test.org.omg.CORBA.portable.InputStream istream)
    {
        throw new test.org.omg.CORBA.MARSHAL ();
    }

    public static void write (test.org.omg.CORBA.portable.OutputStream ostream,
                              test.org.omg.PortableServer.POA value)
    {
        throw new test.org.omg.CORBA.MARSHAL ();
    }

    public static test.org.omg.PortableServer.POA narrow (test.org.omg.CORBA.Object obj)
    {
       if (obj == null)
           return null;
       else if (obj instanceof test.org.omg.PortableServer.POA)
           return (test.org.omg.PortableServer.POA)obj;
       else if (!obj._is_a (id ()))
          throw new test.org.omg.CORBA.BAD_PARAM ();
       return null;
    }
}
