package test.org.omg.PortableServer;


/**
* test.org/omg/PortableServer/ServantActivatorPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/java_re/workspace/8-2-build-macosx-x86_64/jdk8u131/8869/corba/src/share/classes/test.org/omg/PortableServer/poa.idl
* Wednesday, March 15, 2017 1:33:59 AM PDT
*/


/**
	 * When the POA has the RETAIN policy it uses servant 
	 * managers that are ServantActivators. 
	 */
public abstract class ServantActivatorPOA extends test.org.omg.PortableServer.Servant
 implements test.org.omg.PortableServer.ServantActivatorOperations, test.org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("incarnate", new java.lang.Integer (0));
    _methods.put ("etherealize", new java.lang.Integer (1));
  }

  public test.org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                                           test.org.omg.CORBA.portable.InputStream in,
                                                           test.org.omg.CORBA.portable.ResponseHandler $rh)
  {
    throw new test.org.omg.CORBA.BAD_OPERATION();
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:omg.test.org/PortableServer/ServantActivator:2.3",
    "IDL:omg.test.org/PortableServer/ServantManager:1.0"};

  public String[] _all_interfaces (test.org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ServantActivator _this() 
  {
    return ServantActivatorHelper.narrow(
    super._this_object());
  }

  public ServantActivator _this(test.org.omg.CORBA.ORB orb)
  {
    return ServantActivatorHelper.narrow(
    super._this_object(orb));
  }


} // class ServantActivatorPOA
