package test.org.omg.PortableServer;


/**
* test.org/omg/PortableServer/ServantActivatorHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/java_re/workspace/8-2-build-macosx-x86_64/jdk8u131/8869/corba/src/share/classes/test.org/omg/PortableServer/poa.idl
* Wednesday, March 15, 2017 1:33:59 AM PDT
*/


/**
	 * When the POA has the RETAIN policy it uses servant 
	 * managers that are ServantActivators. 
	 */
abstract public class ServantActivatorHelper
{
  private static String  _id = "IDL:omg.test.org/PortableServer/ServantActivator:2.3";

  public static void insert (test.org.omg.CORBA.Any a, test.org.omg.PortableServer.ServantActivator that)
  {
    test.org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static test.org.omg.PortableServer.ServantActivator extract (test.org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static test.org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static test.org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = test.org.omg.CORBA.ORB.init ().create_interface_tc (test.org.omg.PortableServer.ServantActivatorHelper.id (), "ServantActivator");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static test.org.omg.PortableServer.ServantActivator read (test.org.omg.CORBA.portable.InputStream istream)
  {
      throw new test.org.omg.CORBA.MARSHAL ();
  }

  public static void write (test.org.omg.CORBA.portable.OutputStream ostream, test.org.omg.PortableServer.ServantActivator value)
  {
      throw new test.org.omg.CORBA.MARSHAL ();
  }

  public static test.org.omg.PortableServer.ServantActivator narrow (test.org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof test.org.omg.PortableServer.ServantActivator)
      return (test.org.omg.PortableServer.ServantActivator)obj;
    else if (!obj._is_a (id ()))
      throw new test.org.omg.CORBA.BAD_PARAM ();
    else
    {
      test.org.omg.CORBA.portable.Delegate delegate = ((test.org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      test.org.omg.PortableServer._ServantActivatorStub stub = new test.org.omg.PortableServer._ServantActivatorStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static test.org.omg.PortableServer.ServantActivator unchecked_narrow (test.org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof test.org.omg.PortableServer.ServantActivator)
      return (test.org.omg.PortableServer.ServantActivator)obj;
    else
    {
      test.org.omg.CORBA.portable.Delegate delegate = ((test.org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      test.org.omg.PortableServer._ServantActivatorStub stub = new test.org.omg.PortableServer._ServantActivatorStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
