/*
 * Copyright (c) 1999, 2001, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */
package test.org.omg.CORBA;


/**
* The Helper for <tt>Current</tt>.  For more information on
* Helper files, see <a href="doc-files/generatedfiles.html#helper">
* "Generated Files: Helper Files"</a>.<P>
* test.org/omg/CORBA/CurrentHelper.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from ../../../../../src/share/classes/test.org/omg/PortableServer/corba.idl
* Saturday, July 17, 1999 12:26:21 AM PDT
*/

abstract public class CurrentHelper
{
  private static String  _id = "IDL:omg.test.org/CORBA/Current:1.0";

  public static void insert (test.org.omg.CORBA.Any a, test.org.omg.CORBA.Current that)
  {
    throw new test.org.omg.CORBA.MARSHAL() ;
  }

  public static test.org.omg.CORBA.Current extract (test.org.omg.CORBA.Any a)
  {
    throw new test.org.omg.CORBA.MARSHAL() ;
  }

  private static test.org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static test.org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = test.org.omg.CORBA.ORB.init ().create_interface_tc (test.org.omg.CORBA.CurrentHelper.id (), "Current");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static test.org.omg.CORBA.Current read (test.org.omg.CORBA.portable.InputStream istream)
  {
    throw new test.org.omg.CORBA.MARSHAL() ;
  }

  public static void write (test.org.omg.CORBA.portable.OutputStream ostream, test.org.omg.CORBA.Current value)
  {
    throw new test.org.omg.CORBA.MARSHAL() ;
  }

  public static test.org.omg.CORBA.Current narrow (test.org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof test.org.omg.CORBA.Current)
      return (test.org.omg.CORBA.Current)obj;
    else
      throw new test.org.omg.CORBA.BAD_PARAM ();
  }

}
