package test.org.omg.CORBA;


/**
* test.org/omg/CORBA/ParameterModeHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/java_re/workspace/8-2-build-macosx-x86_64/jdk8u131/8869/corba/src/share/classes/test.org/omg/PortableInterceptor/CORBAX.idl
* Wednesday, March 15, 2017 1:33:58 AM PDT
*/


/**
   * Enumeration of parameter modes for Parameter.  Possible vaues:
   * <ul>
   *   <li>PARAM_IN - Represents an "in" parameter.</li>
   *   <li>PARAM_OUT - Represents an "out" parameter.</li>
   *   <li>PARAM_INOUT - Represents an "inout" parameter.</li>
   * </ul>
   */
abstract public class ParameterModeHelper
{
  private static String  _id = "IDL:omg.test.org/CORBA/ParameterMode:1.0";

  public static void insert (test.org.omg.CORBA.Any a, test.org.omg.CORBA.ParameterMode that)
  {
    test.org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static test.org.omg.CORBA.ParameterMode extract (test.org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static test.org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static test.org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = test.org.omg.CORBA.ORB.init ().create_enum_tc (test.org.omg.CORBA.ParameterModeHelper.id (), "ParameterMode", new String[] { "PARAM_IN", "PARAM_OUT", "PARAM_INOUT"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static test.org.omg.CORBA.ParameterMode read (test.org.omg.CORBA.portable.InputStream istream)
  {
    return test.org.omg.CORBA.ParameterMode.from_int (istream.read_long ());
  }

  public static void write (test.org.omg.CORBA.portable.OutputStream ostream, test.org.omg.CORBA.ParameterMode value)
  {
    ostream.write_long (value.value ());
  }

}
