package test.org.omg.CORBA;


/**
* test.org/omg/CORBA/PolicyErrorHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/java_re/workspace/8-2-build-macosx-x86_64/jdk8u131/8869/corba/src/share/classes/test.org/omg/PortableInterceptor/CORBAX.idl
* Wednesday, March 15, 2017 1:33:58 AM PDT
*/


/**
   * Thrown to indicate problems with parameter values passed to the
   * <code>ORB.create_policy</code> operation.  
   */
abstract public class PolicyErrorHelper
{
  private static String  _id = "IDL:omg.test.org/CORBA/PolicyError:1.0";

  public static void insert (test.org.omg.CORBA.Any a, test.org.omg.CORBA.PolicyError that)
  {
    test.org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static test.org.omg.CORBA.PolicyError extract (test.org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static test.org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static test.org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (test.org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return test.org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          test.org.omg.CORBA.StructMember[] _members0 = new test.org.omg.CORBA.StructMember [1];
          test.org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = test.org.omg.CORBA.ORB.init ().get_primitive_tc (test.org.omg.CORBA.TCKind.tk_short);
          _tcOf_members0 = test.org.omg.CORBA.ORB.init ().create_alias_tc (test.org.omg.CORBA.PolicyErrorCodeHelper.id (), "PolicyErrorCode", _tcOf_members0);
          _members0[0] = new test.org.omg.CORBA.StructMember (
            "reason",
            _tcOf_members0,
            null);
          __typeCode = test.org.omg.CORBA.ORB.init ().create_exception_tc (test.org.omg.CORBA.PolicyErrorHelper.id (), "PolicyError", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static test.org.omg.CORBA.PolicyError read (test.org.omg.CORBA.portable.InputStream istream)
  {
    test.org.omg.CORBA.PolicyError value = new test.org.omg.CORBA.PolicyError ();
    // read and discard the repository ID
    istream.read_string ();
    value.reason = istream.read_short ();
    return value;
  }

  public static void write (test.org.omg.CORBA.portable.OutputStream ostream, test.org.omg.CORBA.PolicyError value)
  {
    // write the repository ID
    ostream.write_string (id ());
    ostream.write_short (value.reason);
  }

}
