/*
 * Copyright (c) 1999, 2001, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */
package test.org.omg.CORBA;


/**
* The Helper for <tt>Policy</tt>.  For more information on
* Helper files, see <a href="doc-files/generatedfiles.html#helper">
* "Generated Files: Helper Files"</a>.<P>
* test.org/omg/CORBA/PolicyHelper.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from ../../../../../src/share/classes/test.org/omg/PortableServer/corba.idl
* Saturday, July 17, 1999 12:26:20 AM PDT
*/

abstract public class PolicyHelper
{
  private static String  _id = "IDL:omg.test.org/CORBA/Policy:1.0";

  public static void insert (test.org.omg.CORBA.Any a, test.org.omg.CORBA.Policy that)
  {
    test.org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static test.org.omg.CORBA.Policy extract (test.org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static test.org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static test.org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = test.org.omg.CORBA.ORB.init ().create_interface_tc (test.org.omg.CORBA.PolicyHelper.id (), "Policy");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static test.org.omg.CORBA.Policy read (test.org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_PolicyStub.class));
  }

  public static void write (test.org.omg.CORBA.portable.OutputStream ostream, test.org.omg.CORBA.Policy value)
  {
    ostream.write_Object ((test.org.omg.CORBA.Object) value);
  }

  public static test.org.omg.CORBA.Policy narrow (test.org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof test.org.omg.CORBA.Policy)
      return (test.org.omg.CORBA.Policy)obj;
    else if (!obj._is_a (id ()))
      throw new test.org.omg.CORBA.BAD_PARAM ();
    else
    {
      test.org.omg.CORBA.portable.Delegate delegate = ((test.org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      return new test.org.omg.CORBA._PolicyStub (delegate);
    }
  }

}
