/*
 * Copyright (c) 1999, 2001, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */
package test.org.omg.CORBA;


/**
* The Helper for <tt>ValueMember</tt>.  For more information on
* Helper files, see <a href="doc-files/generatedfiles.html#helper">
* "Generated Files: Helper Files"</a>.<P>
* test.org/omg/CORBA/ValueMemberHelper.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from ir.idl
* 03 June 1999 11:33:44 o'clock GMT+00:00
*/

abstract public class ValueMemberHelper
{
  private static String  _id = "IDL:omg.test.org/CORBA/ValueMember:1.0";

  public static void insert (test.org.omg.CORBA.Any a, test.org.omg.CORBA.ValueMember that)
  {
    test.org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static test.org.omg.CORBA.ValueMember extract (test.org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static test.org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static test.org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (test.org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return test.org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          test.org.omg.CORBA.StructMember[] _members0 = new test.org.omg.CORBA.StructMember [7];
          test.org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = test.org.omg.CORBA.ORB.init ().create_string_tc (0);
          _tcOf_members0 = test.org.omg.CORBA.ORB.init ().create_alias_tc (test.org.omg.CORBA.IdentifierHelper.id (), "Identifier", _tcOf_members0);
          _members0[0] = new test.org.omg.CORBA.StructMember (
            "name",
            _tcOf_members0,
            null);
          _tcOf_members0 = test.org.omg.CORBA.ORB.init ().create_string_tc (0);
          _tcOf_members0 = test.org.omg.CORBA.ORB.init ().create_alias_tc (test.org.omg.CORBA.RepositoryIdHelper.id (), "RepositoryId", _tcOf_members0);
          _members0[1] = new test.org.omg.CORBA.StructMember (
            "id",
            _tcOf_members0,
            null);
          _tcOf_members0 = test.org.omg.CORBA.ORB.init ().create_string_tc (0);
          _tcOf_members0 = test.org.omg.CORBA.ORB.init ().create_alias_tc (test.org.omg.CORBA.RepositoryIdHelper.id (), "RepositoryId", _tcOf_members0);
          _members0[2] = new test.org.omg.CORBA.StructMember (
            "defined_in",
            _tcOf_members0,
            null);
          _tcOf_members0 = test.org.omg.CORBA.ORB.init ().create_string_tc (0);
          _tcOf_members0 = test.org.omg.CORBA.ORB.init ().create_alias_tc (test.org.omg.CORBA.VersionSpecHelper.id (), "VersionSpec", _tcOf_members0);
          _members0[3] = new test.org.omg.CORBA.StructMember (
            "version",
            _tcOf_members0,
            null);
          _tcOf_members0 = test.org.omg.CORBA.ORB.init ().get_primitive_tc (test.org.omg.CORBA.TCKind.tk_TypeCode);
          _members0[4] = new test.org.omg.CORBA.StructMember (
            "type",
            _tcOf_members0,
            null);
          _tcOf_members0 = test.org.omg.CORBA.IDLTypeHelper.type ();
          _members0[5] = new test.org.omg.CORBA.StructMember (
            "type_def",
            _tcOf_members0,
            null);
          _tcOf_members0 = test.org.omg.CORBA.ORB.init ().get_primitive_tc (test.org.omg.CORBA.TCKind.tk_short);
          _tcOf_members0 = test.org.omg.CORBA.ORB.init ().create_alias_tc (test.org.omg.CORBA.VisibilityHelper.id (), "Visibility", _tcOf_members0);
          _members0[6] = new test.org.omg.CORBA.StructMember (
            "access",
            _tcOf_members0,
            null);
          __typeCode = test.org.omg.CORBA.ORB.init ().create_struct_tc (test.org.omg.CORBA.ValueMemberHelper.id (), "ValueMember", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static test.org.omg.CORBA.ValueMember read (test.org.omg.CORBA.portable.InputStream istream)
  {
    test.org.omg.CORBA.ValueMember value = new test.org.omg.CORBA.ValueMember ();
    value.name = istream.read_string ();
    value.id = istream.read_string ();
    value.defined_in = istream.read_string ();
    value.version = istream.read_string ();
    value.type = istream.read_TypeCode ();
    value.type_def = test.org.omg.CORBA.IDLTypeHelper.read (istream);
    value.access = istream.read_short ();
    return value;
  }

  public static void write (test.org.omg.CORBA.portable.OutputStream ostream, test.org.omg.CORBA.ValueMember value)
  {
    ostream.write_string (value.name);
    ostream.write_string (value.id);
    ostream.write_string (value.defined_in);
    ostream.write_string (value.version);
    ostream.write_TypeCode (value.type);
    test.org.omg.CORBA.IDLTypeHelper.write (ostream, value.type_def);
    ostream.write_short (value.access);
  }

}
