/*
 * Copyright (c) 2000, 2001, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */
package test.org.omg.CORBA;

/**
* The Holder for <tt>WrongTransaction</tt>.  For more information on
* Holder files, see <a href="doc-files/generatedfiles.html#holder">
* "Generated Files: Holder Files"</a>.<P>
* test.org/omg/CORBA/WrongTransactionHolder.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from CORBA.idl
* Thursday, August 24, 2000 5:32:50 PM PDT
*/

public final class WrongTransactionHolder implements test.org.omg.CORBA.portable.Streamable
{
  public test.org.omg.CORBA.WrongTransaction value = null;

  public WrongTransactionHolder ()
  {
  }

  public WrongTransactionHolder (test.org.omg.CORBA.WrongTransaction initialValue)
  {
    value = initialValue;
  }

  public void _read (test.org.omg.CORBA.portable.InputStream i)
  {
    value = test.org.omg.CORBA.WrongTransactionHelper.read (i);
  }

  public void _write (test.org.omg.CORBA.portable.OutputStream o)
  {
    test.org.omg.CORBA.WrongTransactionHelper.write (o, value);
  }

  public test.org.omg.CORBA.TypeCode _type ()
  {
    return test.org.omg.CORBA.WrongTransactionHelper.type ();
  }

}
