package test.org.omg.CosNaming.NamingContextPackage;


/**
* test.org/omg/CosNaming/NamingContextPackage/CannotProceedHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/java_re/workspace/8-2-build-macosx-x86_64/jdk8u131/8869/corba/src/share/classes/test.org/omg/CosNaming/nameservice.idl
* Wednesday, March 15, 2017 1:33:57 AM PDT
*/

abstract public class CannotProceedHelper
{
  private static String  _id = "IDL:omg.test.org/CosNaming/NamingContext/CannotProceed:1.0";

  public static void insert (test.org.omg.CORBA.Any a, test.org.omg.CosNaming.NamingContextPackage.CannotProceed that)
  {
    test.org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static test.org.omg.CosNaming.NamingContextPackage.CannotProceed extract (test.org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static test.org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static test.org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (test.org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return test.org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          test.org.omg.CORBA.StructMember[] _members0 = new test.org.omg.CORBA.StructMember [2];
          test.org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = test.org.omg.CosNaming.NamingContextHelper.type ();
          _members0[0] = new test.org.omg.CORBA.StructMember (
            "cxt",
            _tcOf_members0,
            null);
          _tcOf_members0 = test.org.omg.CosNaming.NameComponentHelper.type ();
          _tcOf_members0 = test.org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = test.org.omg.CORBA.ORB.init ().create_alias_tc (test.org.omg.CosNaming.NameHelper.id (), "Name", _tcOf_members0);
          _members0[1] = new test.org.omg.CORBA.StructMember (
            "rest_of_name",
            _tcOf_members0,
            null);
          __typeCode = test.org.omg.CORBA.ORB.init ().create_exception_tc (test.org.omg.CosNaming.NamingContextPackage.CannotProceedHelper.id (), "CannotProceed", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static test.org.omg.CosNaming.NamingContextPackage.CannotProceed read (test.org.omg.CORBA.portable.InputStream istream)
  {
    test.org.omg.CosNaming.NamingContextPackage.CannotProceed value = new test.org.omg.CosNaming.NamingContextPackage.CannotProceed ();
    // read and discard the repository ID
    istream.read_string ();
    value.cxt = test.org.omg.CosNaming.NamingContextHelper.read (istream);
    value.rest_of_name = test.org.omg.CosNaming.NameHelper.read (istream);
    return value;
  }

  public static void write (test.org.omg.CORBA.portable.OutputStream ostream, test.org.omg.CosNaming.NamingContextPackage.CannotProceed value)
  {
    // write the repository ID
    ostream.write_string (id ());
    test.org.omg.CosNaming.NamingContextHelper.write (ostream, value.cxt);
    test.org.omg.CosNaming.NameHelper.write (ostream, value.rest_of_name);
  }

}
