package test.org.omg.CosNaming.NamingContextPackage;


/**
* test.org/omg/CosNaming/NamingContextPackage/NotFoundReasonHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/java_re/workspace/8-2-build-macosx-x86_64/jdk8u131/8869/corba/src/share/classes/test.org/omg/CosNaming/nameservice.idl
* Wednesday, March 15, 2017 1:33:57 AM PDT
*/


/**
         * Indicates the reason for not able to resolve.
         */
abstract public class NotFoundReasonHelper
{
  private static String  _id = "IDL:omg.test.org/CosNaming/NamingContext/NotFoundReason:1.0";

  public static void insert (test.org.omg.CORBA.Any a, test.org.omg.CosNaming.NamingContextPackage.NotFoundReason that)
  {
    test.org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static test.org.omg.CosNaming.NamingContextPackage.NotFoundReason extract (test.org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static test.org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static test.org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = test.org.omg.CORBA.ORB.init ().create_enum_tc (test.org.omg.CosNaming.NamingContextPackage.NotFoundReasonHelper.id (), "NotFoundReason", new String[] { "missing_node", "not_context", "not_object"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static test.org.omg.CosNaming.NamingContextPackage.NotFoundReason read (test.org.omg.CORBA.portable.InputStream istream)
  {
    return test.org.omg.CosNaming.NamingContextPackage.NotFoundReason.from_int (istream.read_long ());
  }

  public static void write (test.org.omg.CORBA.portable.OutputStream ostream, test.org.omg.CosNaming.NamingContextPackage.NotFoundReason value)
  {
    ostream.write_long (value.value ());
  }

}
