package test.org.omg.CosNaming;


/**
* test.org/omg/CosNaming/BindingIteratorHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/java_re/workspace/8-2-build-macosx-x86_64/jdk8u131/8869/corba/src/share/classes/test.org/omg/CosNaming/nameservice.idl
* Wednesday, March 15, 2017 1:33:57 AM PDT
*/


/**
   * The BindingIterator interface allows a client to iterate through
   * the bindings using the next_one or next_n operations.
   * 
   * The bindings iterator is obtained by using the <tt>list</tt>
   * method on the <tt>NamingContext</tt>. 
   * @see test.org.omg.CosNaming.NamingContext#list
   */
abstract public class BindingIteratorHelper
{
  private static String  _id = "IDL:omg.test.org/CosNaming/BindingIterator:1.0";

  public static void insert (test.org.omg.CORBA.Any a, test.org.omg.CosNaming.BindingIterator that)
  {
    test.org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static test.org.omg.CosNaming.BindingIterator extract (test.org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static test.org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static test.org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = test.org.omg.CORBA.ORB.init ().create_interface_tc (test.org.omg.CosNaming.BindingIteratorHelper.id (), "BindingIterator");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static test.org.omg.CosNaming.BindingIterator read (test.org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_BindingIteratorStub.class));
  }

  public static void write (test.org.omg.CORBA.portable.OutputStream ostream, test.org.omg.CosNaming.BindingIterator value)
  {
    ostream.write_Object ((test.org.omg.CORBA.Object) value);
  }

  public static test.org.omg.CosNaming.BindingIterator narrow (test.org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof test.org.omg.CosNaming.BindingIterator)
      return (test.org.omg.CosNaming.BindingIterator)obj;
    else if (!obj._is_a (id ()))
      throw new test.org.omg.CORBA.BAD_PARAM ();
    else
    {
      test.org.omg.CORBA.portable.Delegate delegate = ((test.org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      test.org.omg.CosNaming._BindingIteratorStub stub = new test.org.omg.CosNaming._BindingIteratorStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static test.org.omg.CosNaming.BindingIterator unchecked_narrow (test.org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof test.org.omg.CosNaming.BindingIterator)
      return (test.org.omg.CosNaming.BindingIterator)obj;
    else
    {
      test.org.omg.CORBA.portable.Delegate delegate = ((test.org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      test.org.omg.CosNaming._BindingIteratorStub stub = new test.org.omg.CosNaming._BindingIteratorStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
