package test.org.omg.CosNaming;


/**
* test.org/omg/CosNaming/Binding.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/java_re/workspace/8-2-build-macosx-x86_64/jdk8u131/8869/corba/src/share/classes/test.org/omg/CosNaming/nameservice.idl
* Wednesday, March 15, 2017 1:33:57 AM PDT
*/

public final class Binding implements test.org.omg.CORBA.portable.IDLEntity
{
  public test.org.omg.CosNaming.NameComponent binding_name[] = null;

  // name
  public test.org.omg.CosNaming.BindingType binding_type = null;

  public Binding ()
  {
  } // ctor

  public Binding (test.org.omg.CosNaming.NameComponent[] _binding_name, test.org.omg.CosNaming.BindingType _binding_type)
  {
    binding_name = _binding_name;
    binding_type = _binding_type;
  } // ctor

} // class Binding
