package test.org.omg.CosNaming;


/**
* test.org/omg/CosNaming/BindingTypeHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/java_re/workspace/8-2-build-macosx-x86_64/jdk8u131/8869/corba/src/share/classes/test.org/omg/CosNaming/nameservice.idl
* Wednesday, March 15, 2017 1:33:57 AM PDT
*/


/**
   * Specifies whether the given binding is for a object (that is not a
   * naming context) or for a naming context.
   */
abstract public class BindingTypeHelper
{
  private static String  _id = "IDL:omg.test.org/CosNaming/BindingType:1.0";

  public static void insert (test.org.omg.CORBA.Any a, test.org.omg.CosNaming.BindingType that)
  {
    test.org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static test.org.omg.CosNaming.BindingType extract (test.org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static test.org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static test.org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = test.org.omg.CORBA.ORB.init ().create_enum_tc (test.org.omg.CosNaming.BindingTypeHelper.id (), "BindingType", new String[] { "nobject", "ncontext"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static test.org.omg.CosNaming.BindingType read (test.org.omg.CORBA.portable.InputStream istream)
  {
    return test.org.omg.CosNaming.BindingType.from_int (istream.read_long ());
  }

  public static void write (test.org.omg.CORBA.portable.OutputStream ostream, test.org.omg.CosNaming.BindingType value)
  {
    ostream.write_long (value.value ());
  }

}
